<?php

namespace MediaWiki\Extension\AssistedSearch;

use MediaWiki\MediaWikiServices;
use MediaWiki\Parser\Sanitizer;
use MediaWiki\Title\Title;

class SectionExtractor {

	// section_id format: "DBkey" or "DBkey#anchor"
	// - DBkey is the MediaWiki database key (getPrefixedDBkey), e.g. "M.U.L.E." or "Größe"
	// - anchor is generated by Sanitizer::escapeIdForLink(), which is what MW puts in HTML <a id="...">
	//   e.g. "Überblick" becomes ".C3.9Cberblick" (dot-separated hex bytes for non-ASCII)
	// - This is NOT rawurlencode — rawurlencode would produce "%C3%9Cberblick" which won't
	//   match the on-page anchor, causing section links to scroll to the wrong position
	// - When looking up a section by section_id, we compare the fragment directly against
	//   Sanitizer::escapeId() of each heading, rather than trying to reverse the encoding

	public function __construct() {
	}

	/**
	 * @return array<int, array{article_title: string, section_heading: string, section_text: string, section_id: string, section_index: int}>
	 */
	public function extractAllSections( \WikiPage $page ): array {
		$content = $page->getContent();
		if ( !$content ) {
			return [];
		}

		$wikitext = $content->getText();
		$headings = $this->parseHeadings( $wikitext );
		$title = $page->getTitle();
		$dbkey = $title->getPrefixedDBkey();
		$sections = [];

		$sectionContent = $content->getSection( '0' );
		if ( $sectionContent ) {
			$sections[] = [
				'article_title' => $title->getFullText(),
				'section_heading' => '',
				'section_text' => WikitextCleaner::cleanText( $sectionContent->getTextForSearchIndex() ),
				'section_id' => $dbkey,
				'section_index' => 0,
			];
		}

		foreach ( $headings as $i => $heading ) {
			$sectionId = (string)( $i + 1 );
			$sectionContent = $content->getSection( $sectionId );
			if ( $sectionContent ) {
				$anchor = $this->makeAnchor( $heading );
				$sections[] = [
					'article_title' => $title->getFullText(),
					'section_heading' => $heading,
					'section_text' => WikitextCleaner::cleanText( $sectionContent->getTextForSearchIndex() ),
					'section_id' => $dbkey . '#' . $anchor,
					'section_index' => $i + 1,
				];
			}
		}

		return $sections;
	}

	public function getSectionById( string $sectionId ): ?array {
		[ $titleText, $fragment ] = $this->parseSectionId( $sectionId );
		if ( $titleText === null ) {
			return null;
		}

		$title = Title::newFromText( $titleText );
		if ( !$title ) {
			return null;
		}

		$wikiPage = MediaWikiServices::getInstance()
			->getWikiPageFactory()
			->newFromTitle( $title );

		if ( !$wikiPage->exists() ) {
			return null;
		}

		$content = $wikiPage->getContent();
		if ( !$content ) {
			return null;
		}

		$dbkey = $title->getPrefixedDBkey();

		if ( $fragment === '' ) {
			$sectionContent = $content->getSection( '0' );
			if ( !$sectionContent ) {
				return null;
			}
			return [
				'article_title' => $title->getFullText(),
				'section_heading' => '',
				'section_text' => WikitextCleaner::cleanText( $sectionContent->getTextForSearchIndex() ),
				'section_id' => $dbkey,
				'section_index' => 0,
			];
		}

		$headingText = $fragment;
		$headings = $this->parseHeadings( $content->getText() );

		foreach ( $headings as $i => $heading ) {
			$anchor = $this->makeAnchor( $heading );
			if ( $anchor === $headingText ) {
				$sectionContent = $content->getSection( (string)( $i + 1 ) );
				if ( $sectionContent ) {
					return [
						'article_title' => $title->getFullText(),
						'section_heading' => $heading,
						'section_text' => WikitextCleaner::cleanText( $sectionContent->getTextForSearchIndex() ),
						'section_id' => $dbkey . '#' . $anchor,
						'section_index' => $i + 1,
					];
				}
			}
		}

		return null;
	}

	public function getAdjacentSection( string $sectionId, string $direction ): ?array {
		[ $titleText, $fragment ] = $this->parseSectionId( $sectionId );
		if ( $titleText === null ) {
			return null;
		}

		$title = Title::newFromText( $titleText );
		if ( !$title ) {
			return null;
		}

		$wikiPage = MediaWikiServices::getInstance()
			->getWikiPageFactory()
			->newFromTitle( $title );

		if ( !$wikiPage->exists() ) {
			return null;
		}

		$content = $wikiPage->getContent();
		if ( !$content ) {
			return null;
		}

		$headings = $this->parseHeadings( $content->getText() );
		$dbkey = $title->getPrefixedDBkey();

		if ( $fragment === '' ) {
			if ( $direction === 'next' && count( $headings ) > 0 ) {
				$heading = $headings[0];
				$sectionContent = $content->getSection( '1' );
				if ( $sectionContent ) {
					$anchor = $this->makeAnchor( $heading );
					return [
						'article_title' => $title->getFullText(),
						'section_heading' => $heading,
						'section_text' => WikitextCleaner::cleanText( $sectionContent->getTextForSearchIndex() ),
						'section_id' => $dbkey . '#' . $anchor,
						'section_index' => 1,
					];
				}
			}
			return null;
		}

		$headingText = $fragment;
		$currentIndex = -1;
		foreach ( $headings as $i => $heading ) {
			$anchor = $this->makeAnchor( $heading );
			if ( $anchor === $headingText ) {
				$currentIndex = $i;
				break;
			}
		}

		if ( $currentIndex === -1 ) {
			return null;
		}

		$targetIndex = $direction === 'next' ? $currentIndex + 1 : $currentIndex - 1;

		if ( $targetIndex < 0 ) {
			$sectionContent = $content->getSection( '0' );
			if ( $sectionContent ) {
				return [
					'article_title' => $title->getFullText(),
					'section_heading' => '',
					'section_text' => WikitextCleaner::cleanText( $sectionContent->getTextForSearchIndex() ),
					'section_id' => $dbkey,
					'section_index' => 0,
				];
			}
			return null;
		}

		if ( $targetIndex >= count( $headings ) ) {
			return null;
		}

		$heading = $headings[$targetIndex];
		$sectionContent = $content->getSection( (string)( $targetIndex + 1 ) );
		if ( $sectionContent ) {
			$anchor = $this->makeAnchor( $heading );
			return [
				'article_title' => $title->getFullText(),
				'section_heading' => $heading,
				'section_text' => WikitextCleaner::cleanText( $sectionContent->getTextForSearchIndex() ),
				'section_id' => $dbkey . '#' . $anchor,
				'section_index' => $targetIndex + 1,
			];
		}

		return null;
	}

	public function makeFullUrl( string $sectionId ): string {
		[ $titleText, $fragment ] = $this->parseSectionId( $sectionId );
		$title = Title::newFromText( $titleText );
		if ( !$title ) {
			return '';
		}
		$url = $title->getFullURL();
		if ( $fragment !== '' ) {
			$url .= '#' . $fragment;
		}
		return $url;
	}

	// Parses "Title#anchor" into [titleText, fragment].
	// titleText is rawurldecoded so Title::newFromText() can handle it.
	// fragment is left as-is (MW-escaped) for direct anchor comparison.
	private function parseSectionId( string $sectionId ): array {
		if ( str_contains( $sectionId, '#' ) ) {
			[ $titlePart, $fragment ] = explode( '#', $sectionId, 2 );
			return [ rawurldecode( $titlePart ), $fragment ];
		}
		return [ rawurldecode( $sectionId ), '' ];
	}

	/**
	 * @return string[]
	 */
	private function parseHeadings( string $wikitext ): array {
		$headings = [];
		if ( preg_match_all( '/^(={1,6})\s*(.+?)\s*\1\s*$/m', $wikitext, $matches, PREG_SET_ORDER ) ) {
			foreach ( $matches as $match ) {
				$headings[] = $match[2];
			}
		}
		return $headings;
	}

	// Converts a heading to the same format MW uses in HTML anchors.
	// Must match Sanitizer::escapeIdForLink() — not rawurlencode — so that
	// #fragment links in URLs scroll to the correct heading.
	private function makeAnchor( string $heading ): string {
		return Sanitizer::escapeIdForLink( str_replace( ' ', '_', $heading ) );
	}

}
